apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: voto
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: voto
    app.kubernetes.io/part-of: byoc-app-vwcx
  name: voto
spec:
  rules:
  - host: voto-byoc-kvvf-tenant.apps.a33c54d7af23889fe71a.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: voto
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
