apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: voto
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: voto
    app.kubernetes.io/part-of: byoc-app-vwcx
  name: voto
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: voto
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: voto
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-kvvf-tenant/byoc-app-vwcx/voto@sha256:6a5702d407719dcb8ca02b6465d4982b0c5d7b325d71f94e1ccb145391dd542f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
